version: '3'

services:

  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - 9999:9999
    user: root
    working_dir: /home/jupyter/work
    volumes:
      - ./jupyter:/home/jupyter/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_USER=jupyter
      - NB_UID=1001
      - NB_GID=1001
      - CHOWN_HOME=yes
    command: start-notebook.sh --NotebookApp.token='changethis' --no-browser --allow-root --notebook-dir=/home/jupyter/work --port 9999
    
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
